[project]
name = "promptweaver"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "crewai",
  "docling>=2.30.0",
  "openai",
  "python-dotenv",
  "streamlit",  # Added for Streamlit UI
]

[tool.crewai]
entry_point = "src/main.py"
